# Generated by Django 4.2.4 on 2023-08-09 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='form',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Blog', models.CharField(max_length=50)),
                ('Contant', models.CharField(max_length=500)),
                ('Create', models.DateTimeField(max_length=100)),
                ('Update', models.DateTimeField(max_length=100)),
            ],
        ),
    ]
