# Generated by Django 4.2.4 on 2023-08-05 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pepole', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='register',
            name='propic',
            field=models.FileField(default='pepole.jpg', upload_to='midia/'),
        ),
    ]
