# Generated by Django 4.2.4 on 2023-08-05 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pepole', '0002_register_propic'),
    ]

    operations = [
        migrations.AddField(
            model_name='register',
            name='address',
            field=models.TextField(default=True, max_length=200),
        ),
    ]
