# Generated by Django 4.2.4 on 2023-08-05 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pepole', '0004_alter_register_propic'),
    ]

    operations = [
        migrations.CreateModel(
            name='notc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('notice', models.CharField(max_length=500)),
                ('date', models.DateField(max_length=50)),
            ],
        ),
    ]
