# Generated by Django 4.2.4 on 2023-08-07 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pepole', '0005_notc'),
    ]

    operations = [
        migrations.CreateModel(
            name='S_watchmen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('w_propic', models.FileField(default='pepole.jpg', upload_to='watchmen/')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=50)),
                ('gat_no', models.CharField(max_length=10)),
                ('mobile', models.CharField(max_length=12)),
            ],
        ),
    ]
