# Generated by Django 4.2.4 on 2023-08-08 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pepole', '0006_s_watchmen'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('E_images', models.FileField(default='pepole.jpg', upload_to='event/')),
                ('E_name', models.CharField(max_length=100)),
                ('E_date', models.DateField(max_length=10)),
                ('E_time', models.TimeField(max_length=10)),
                ('E_releted', models.CharField(max_length=500)),
            ],
        ),
    ]
